-- ============================================================
-- Hanna & Nour - Seed data (part 1: promo + 6 products)
-- ============================================================

insert into promo_codes (code, percent_off, active, single_use) values
  ('WELCOME15', 15, true, false)
on conflict (code) do nothing;

insert into products (
  slug, sku, category, price_cents, compare_at_price_cents,
  name_en, name_fr, name_ar,
  description_en, description_fr, description_ar,
  features_en, features_fr, features_ar,
  fabric_comp_en, fabric_comp_fr, fabric_comp_ar,
  care_en, care_fr, care_ar,
  colors, sizes, fabrics, occasions, image, gallery,
  rating, review_count, badge, is_featured, is_bestseller, active
) values
(
  'silk-hijab', 'HN-SH-001', 'hijab', 3500, 4500,
  'Silk Blend Hijab', 'Hijab en soie mélangée', 'حجاب حريري',
  $$The best-selling Silk Blend Hijab is crafted from a luxurious blend of 70% mulberry silk and 30% cotton, for a perfect balance of elegance and practicality. The fabric glides across the skin, stays in place without pins, and drapes beautifully all day.$$,
  $$Le hijab en soie mélangée le plus vendu, composé de 70 % de soie de mûrier et de 30 % de coton, pour un parfait équilibre entre élégance et praticité. Le tissu glisse sur la peau, tient sans épingles et tombe superbement toute la journée.$$,
  $$الحجاب الحريري الأكثر مبيعًا، مصنوع من مزيج فاخر من 70% حرير التوت و30% قطن، لتوازن مثالي بين الأناقة والعملية. القماش ينزلق على البشرة ويثبت دون دبابيس ويتدلى برشاقة طوال اليوم.$$,
  '["Buttery-soft, natural sheen","Slip-resistant, no pins needed","Breathable, all seasons","UPF 50+ protection"]',
  '["Toucher soyeux, éclat naturel","Antidérapant, sans épingles","Respirant, toutes saisons","Protection UPF 50+"]',
  '["ملمس حريري ناعم","يثبت دون دبابيس","قابل للتنفس لجميع الفصول","حماية UPF 50+"]',
  '70% Mulberry Silk, 30% Egyptian Cotton', '70 % soie de mûrier, 30 % coton égyptien', '70% حرير التوت، 30% قطن مصري',
  '["Hand wash cold or gentle cycle","Use mild detergent, no bleach","Lay flat to dry away from sun","Iron low while slightly damp"]',
  '["Lavage main à froid ou cycle délicat","Détergent doux, sans eau de Javel","Sécher à plat, à l''abri du soleil","Repasser à basse température humide"]',
  '["يُغسل يدويًا بماء بارد أو بدورة لطيفة","منظف خفيف دون مبيض","جففي مسطحًا بعيدًا عن الشمس","اكوي على حرارة منخفضة رطبًا قليلًا"]',
  '["Gold","Bronze","Beige","Espresso","Cream"]',
  '["One Size"]', '["Silk","Cotton"]', '["Everyday","Work"]',
  'images/silk-hijab.jpg',
  '[{"src":"images/silk-hijab.jpg","label":"Gold view"},{"src":"images/everyday-hijab.jpg","label":"Natural view"},{"src":"images/hero.jpg","label":"Lifestyle view"}]',
  4.8, 128, 'Bestseller', true, true, true
),
(
  'flowing-abaya', 'HN-AB-002', 'abaya', 8900, null,
  'Flowing Abaya', 'Abaya fluide', 'عباية انسيابية',
  $$A flowing abaya in premium crepe that moves with you from morning to evening. Tailored for comfort with a relaxed silhouette and sophisticated drape.$$,
  $$Une abaya fluide en crêpe premium qui vous accompagne du matin au soir. Coupe confortable, silhouette décontractée et tombé raffiné.$$,
  $$عباية انسيابية من الكريب الفاخر ترافقك من الصباح إلى المساء. قصّة مريحة بظل فضفاض وتدلٍّ راقٍ.$$,
  '["Relaxed, elegant silhouette","Premium crepe","Versatile, all-day comfort"]',
  '["Silhouette ample et élégante","Crêpe premium","Confort toute la journée"]',
  '["ظلّ فضفاض وأنيق","كريب فاخر","راحة طوال اليوم"]',
  '100% Crepe', '100 % crêpe', '100% كريب',
  '["Dry clean or gentle hand wash","Iron on low inside out"]',
  '["Nettoyage à sec ou lavage main délicat","Repasser à basse température, à l''envers"]',
  '["تنظيف جاف أو غسيل يدوي لطيف","الكي على حرارة منخفضة من الداخل"]',
  '["Charcoal","Espresso","Navy"]',
  '["S","M","L","XL"]', '["Crepe","Chiffon"]', '["Eid","Wedding"]',
  'images/eid-abaya.jpg',
  '[{"src":"images/eid-abaya.jpg","label":"Main view"},{"src":"images/hero.jpg","label":"Detail view"}]',
  4.7, 96, null, true, true, true
),
(
  'prayer-set', 'HN-PW-003', 'prayer', 5500, null,
  'Prayer Set', 'Tenue de prière', 'طقم صلاة',
  $$A complete prayer set designed for comfort and dignity during daily worship. Breathable, beautiful and practical for your spiritual practice.$$,
  $$Une tenue de prière complète, confortable et digne pour le culte quotidien. Respirante, belle et pratique pour votre pratique spirituelle.$$,
  $$طقم صلاة متكامل مصمم للراحة والوقار أثناء العبادة اليومية. قابل للتنفس، جميل وعملي لممارستك الروحية.$$,
  '["Complete set, ready to wear","Breathable, comfortable","Beautiful everyday wear"]',
  '["Tenue complète, prête à porter","Respirante et confortable","Belle au quotidien"]',
  '["طقم كامل جاهز للارتداء","قابل للتنفس ومريح","جميل للاستخدام اليومي"]',
  '60% Cotton, 40% Crepe', '60 % coton, 40 % crêpe', '60% قطن، 40% كريب',
  '["Machine washable gentle","Wash separately first time"]',
  '["Lavable en machine, cycle délicat","Lavage séparé la première fois"]',
  '["يُغسل في الغسالة بدورة لطيفة","يُغسل منفردًا في أول مرة"]',
  '["Sage","Champagne","White"]',
  '["One Size"]', '["Cotton","Crepe"]', '["Prayer"]',
  'images/prayer-wear.jpg',
  '[{"src":"images/prayer-wear.jpg","label":"Main view"},{"src":"images/hero.jpg","label":"Detail view"}]',
  4.9, 74, 'New', true, true, true
),
(
  'modest-dress', 'HN-DR-004', 'dress', 7500, 9500,
  'Modest Maxi Dress', 'Robe longue modeste', 'فستان طويل محتشم',
  $$A timeless modest maxi dress with a flattering silhouette and premium jersey fabric. Perfect for work, Eid and everyday elegance.$$,
  $$Une robe longue modeste intemporelle à la silhouette flatteuse, en jersey premium. Parfaite pour le travail, l''Aïd et l''élégance au quotidien.$$,
  $$فستان طويل محتشم خالد بقصّة أنيقة وقماش جيرسي فاخر. مثالي للعمل والعيد والأناقة اليومية.$$,
  '["Flattering maxi silhouette","Premium jersey, 4-way stretch","Trans-seasonal wear"]',
  '["Silhouette maxi flatteuse","Jersey premium extensible","Portable toute l''année"]',
  '["قصة ماكسي أنيقة","جيرسي فاخر مطاطي","ملائم لجميع الفصول"]',
  '95% Cotton Jersey, 5% Elastane', '95 % jersey coton, 5 % élasthanne', '95% جيرسي قطن، 5% إيلاستان',
  '["Machine wash cold","Do not tumble dry","Iron low"]',
  '["Lavage machine à froid","Pas de sèche-linge","Repasser à basse température"]',
  '["غسل في الغسالة بماء بارد","لا يُجفف في المجفف","الكي على حرارة منخفضة"]',
  '["Black","Espresso","Emerald"]',
  '["XS","S","M","L","XL"]', '["Jersey","Crepe"]', '["Eid","Work"]',
  'images/hero.jpg',
  '[{"src":"images/hero.jpg","label":"Main view"},{"src":"images/eid-abaya.jpg","label":"Detail view"}]',
  4.6, 52, null, false, true, true
),
(
  'pearl-brooch', 'HN-AC-005', 'accessory', 1800, null,
  'Pearl Brooch', 'Broche en perles', 'بروش من اللؤلؤ',
  $$A handcrafted pearl brooch that adds an elegant finishing touch to any hijab or outfit. A timeless accessory, beautifully boxed.$$,
  $$Une broche perlée faite main qui apporte une touche finale élégante à tout hijab ou tenue. Un accessoire intemporel, joliment présenté.$$,
  $$بروش لؤلؤي مصنوع يدويًا يضفي لمسة أنيقة على أي حجاب أو إطلالة. إكسسوار خالد في علبة أنيقة.$$,
  '["Handcrafted details","Chic, versatile styling","Arrives gift-boxed"]',
  '["Détails faits main","Style chic et polyvalent","Livré en coffret cadeau"]',
  '["تفاصيل مصنوعة يدويًا","أنيق ومتعدد الاستخدامات","يصل في علبة هدية"]',
  'Resin pearls, gold-tone metal', 'Perles en résine, métal doré', 'لؤلؤ راتنجي، معدن ذهبي',
  '["Wipe with a soft dry cloth","Keep away from water and perfume"]',
  '["Essuyer avec un chiffon doux et sec","Tenir à l''écart de l''eau et du parfum"]',
  '["يُمسح بقطعة قماش ناعمة جافة","يُحفظ بعيدًا عن الماء والعطر"]',
  '["Pearl","Gold"]',
  '["One Size"]', '[]', '["Wedding","Everyday"]',
  'images/pearl-brooch.jpg',
  '[{"src":"images/pearl-brooch.jpg","label":"Main view"},{"src":"images/hero.jpg","label":"Styling view"}]',
  4.5, 38, null, false, true, true
),
(
  'velvet-abaya', 'HN-AB-006', 'abaya', 12900, null,
  'Velvet Abaya', 'Abaya en velours', 'عباية مخملية',
  $$A rich velvet abaya for evenings and celebrations. Luxurious texture, generous drape, and a modest silhouette that radiates quiet confidence.$$,
  $$Une abaya en velours somptueux pour les soirées et célébrations. Texture luxueuse, tombé généreux et silhouette modeste qui dégage une assurance tranquille.$$,
  $$عباية مخملية فاخرة للسهرات والمناسبات. ملمس فاخر وتدلٍّ انسيابي وقصّة محتشمة تبعث ثقة هادئة.$$,
  '["Rich velvet texture","Generous, flowing drape","Evening-ready elegance"]',
  '["Texture velours riche","Tombé ample et fluide","Élégance des soirées"]',
  '["ملمس مخمل فاخر","تدلٍّ واسع وانسيابي","أناقة السهرات"]',
  '92% Velvet, 8% Elastane', '92 % velours, 8 % élasthanne', '92% فيلفيت، 8% إيلاستان',
  '["Dry clean only","Store on a padded hanger"]',
  '["Nettoyage à sec uniquement","Ranger sur cintre rembourré"]',
  '["تنظيف جاف فقط","يُحفظ على شماعة مبطنة"]',
  '["Burgundy","Espresso","Black"]',
  '["S","M","L","XL"]', '["Velvet"]', '["Eid","Wedding"]',
  'images/velvet-abaya.jpg',
  '[{"src":"images/velvet-abaya.jpg","label":"Main view"},{"src":"images/hero.jpg","label":"Detail view"}]',
  4.9, 67, 'Premium', true, true, true
);