-- ============================================================
-- Hanna & Nour - Seed data (part 2: 6 more products)
-- Run AFTER seed.sql.
-- ============================================================

insert into products (
  slug, sku, category, price_cents, compare_at_price_cents,
  name_en, name_fr, name_ar,
  description_en, description_fr, description_ar,
  features_en, features_fr, features_ar,
  fabric_comp_en, fabric_comp_fr, fabric_comp_ar,
  care_en, care_fr, care_ar,
  colors, sizes, fabrics, occasions, image, gallery,
  rating, review_count, badge, is_featured, is_bestseller, active
) values
(
  'everyday-hijab', 'HN-SH-007', 'hijab', 2200, null,
  'Everyday Cotton Hijab', 'Hijab coton du quotidien', 'حجاب قطني يومي',
  $$Our signature everyday hijab in breathable, pre-washed cotton. Versatile, comfortable, and available in a palette of timeless colors.$$,
  $$Notre hijab signature du quotidien en coton respirant, pré-lavé. Polyvalent, confortable et décliné dans une palette de couleurs intemporelles.$$,
  $$حجابنا اليومي المميز من قطن قابل للتنفس ومغسول مسبقًا. متعدد الاستخدامات ومريح ومتوفر بمجموعة ألوان خالدة.$$,
  '["Pre-washed, soft from day one","Breathable pure cotton","Machine washable"]',
  '["Pré-lavé, doux dès le premier jour","Coton pur respirant","Lavable en machine"]',
  '["مغسول مسبقًا، ناعم من اليوم الأول","قطن نقي قابل للتنفس","يُغسل في الغسالة"]',
  '100% Pre-washed Cotton', '100 % coton pré-lavé', '100% قطن مغسول مسبقًا',
  '["Machine wash warm","Tumble dry low"]',
  '["Lavage machine tiède","Séchage en tambour doux"]',
  '["يُغسل في الغسالة بماء دافئ","مجفف بحرارة منخفضة"]',
  '["White","Cream","Beige","Black"]',
  '["One Size"]', '["Cotton"]', '["Everyday","Travel"]',
  'images/everyday-hijab.jpg',
  '[{"src":"images/everyday-hijab.jpg","label":"Main view"},{"src":"images/hero.jpg","label":"Lifestyle view"}]',
  4.4, 213, null, false, true, true
),
(
  'chiffon-wedding', 'HN-SH-008', 'hijab', 4800, null,
  'Chiffon Wedding Hijab', 'Hijab de mariage en mousseline', 'حجاب زفاف شيفون',
  $$An ethereal chiffon hijab for your most special day. Ultra-soft, light-catching fabric that photographs beautifully and drapes like a dream.$$,
  $$Un hijab en mousseline éthéré pour votre plus beau jour. Tissu ultra-doux et lumineux qui sublime les photos et tombe comme un rêve.$$,
  $$حجاب شيفون ساحر ليومك الأجمل. قماش ناعم للغاية ولمّاع يبدو رائعًا في الصور ويتدلى كالحلم.$$,
  '["Ultra-soft chiffon","Beautiful in photography","Light-catching drape"]',
  '["Mousseline ultra-douce","Sublime en photos","Tombé lumineux"]',
  '["شيفون ناعم للغاية","رائع في الصور","تدلٍّ لامع"]',
  '100% Silk Chiffon', '100 % mousseline de soie', '100% شيفون حرير',
  '["Dry clean only","Steam, do not iron directly"]',
  '["Nettoyage à sec uniquement","Vapeur, ne pas repasser directement"]',
  '["تنظيف جاف فقط","بخار، دون كي مباشر"]',
  '["Ivory","Champagne","Gold"]',
  '["One Size"]', '["Chiffon"]', '["Wedding"]',
  'images/hero.jpg',
  '[{"src":"images/hero.jpg","label":"Main view"},{"src":"images/silk-hijab.jpg","label":"Detail view"}]',
  4.9, 45, 'Limited', false, true, true
),
(
  'embroidered-abaya', 'HN-AB-009', 'abaya', 14900, 16900,
  'Embroidered Abaya', 'Abaya brodée', 'عباية مطرزة',
  $$A statement abaya with delicate hand embroidery along the sleeves and hem. Crafted for celebrations, with a graceful, modest fit.$$,
  $$Une abaya signature avec une délicate broderie main le long des manches et de l''ourlet. Conçue pour les célébrations, avec une coupe modeste et gracieuse.$$,
  $$عباية مميزة بتطريز يدوي دقيق على الأكمام والحواف. مصممة للمناسبات بقصّة محتشمة وراقية.$$,
  '["Hand-embroidered details","Celebration-ready","Graceful modest fit"]',
  '["Détails brodés main","Prête pour les grandes occasions","Coupe modeste et gracieuse"]',
  '["تفاصيل مطرزة يدويًا","جاهزة للمناسبات","قصّة محتشمة ورشيقة"]',
  '100% Chiffon, embroidered sleeves', '100 % mousseline, manches brodées', '100% شيفون بأكمام مطرزة',
  '["Hand wash cold, lay flat","Do not wring"]',
  '["Lavage main à froid, sécher à plat","Ne pas essorer"]',
  '["غسل يدوي بماء بارد وتجفيف مسطح","لا تعصري"]',
  '["Black","Emerald","Charcoal"]',
  '["S","M","L","XL"]', '["Chiffon","Crepe"]', '["Eid","Wedding"]',
  'images/eid-abaya.jpg',
  '[{"src":"images/eid-abaya.jpg","label":"Main view"},{"src":"images/velvet-abaya.jpg","label":"Detail view"}]',
  4.8, 61, null, false, true, true
),
(
  'premium-prayer-set', 'HN-PW-010', 'prayer', 8900, null,
  'Premium Prayer Set', 'Tenue de prière premium', 'طقم صلاة فاخر',
  $$A premium prayer set in a soft silk blend with a beautiful, modest silhouette. Elevated comfort for your daily worship and beyond.$$,
  $$Une tenue de prière premium dans un mélange de soie doux, avec une silhouette modeste et élégante. Confort supérieur pour votre culte au quotidien.$$,
  $$طقم صلاة فاخر من مزيج حرير ناعم بقصّة محتشمة وأنيقة. راحة راقية لعبادتك اليومية.$$,
  '["Soft silk blend","Ankle-length coverage","Breathable, all seasons"]',
  '["Mélange de soie doux","Couverture jusqu''aux chevilles","Respirant, toutes saisons"]',
  '["مزيج حرير ناعم","تغطية حتى الكاحل","قابل للتنفس طوال العام"]',
  '70% Silk, 30% Cotton', '70 % soie, 30 % coton', '70% حرير، 30% قطن',
  '["Hand wash cold","Dry flat"]',
  '["Lavage main à froid","Sécher à plat"]',
  '["غسل يدوي بماء بارد","تجفيف مسطح"]',
  '["Champagne","Blush"]',
  '["One Size"]', '["Silk","Cotton"]', '["Prayer"]',
  'images/prayer-wear.jpg',
  '[{"src":"images/prayer-wear.jpg","label":"Main view"},{"src":"images/silk-hijab.jpg","label":"Detail view"}]',
  4.9, 33, null, false, true, true
),
(
  'jersey-hijab', 'HN-SH-011', 'hijab', 2900, null,
  'Jersey Everyday Hijab', 'Hijab jersey du quotidien', 'حجاب جيرسي يومي',
  $$A stretchy, non-slip jersey hijab that stays perfectly in place from morning to night. The ultimate low-effort, high-style staple.$$,
  $$Un hijab jersey extensible et antidérapant qui reste parfaitement en place du matin au soir. L''indispensable sans effort, plein de style.$$,
  $$حجاب جيرسي مطاطي مانع للانزلاق يثبت مثاليًا من الصباح إلى المساء. أساسي عملي وأنيق بلا مجهود.$$,
  '["Stretchy, one-size fit","Non-slip grip","Wrinkle-resistant"]',
  '["Extensible, taille unique","Adhérence antidérapante","Résiste aux plis"]',
  '["مطاطي بمقاس واحد","مانع للانزلاق","لا يتجعد"]',
  '92% Jersey, 8% Elastane', '92 % jersey, 8 % élasthanne', '92% جيرسي، 8% إيلاستان',
  '["Gentle machine wash","Do not bleach"]',
  '["Lavage machine délicat","Pas d''eau de Javel"]',
  '["غسل في الغسالة بدورة لطيفة","لا تستخدمي المبيض"]',
  '["Black","Nude","Charcoal"]',
  '["One Size"]', '["Jersey"]', '["Everyday","Work"]',
  'images/everyday-hijab.jpg',
  '[{"src":"images/everyday-hijab.jpg","label":"Main view"},{"src":"images/hero.jpg","label":"Lifestyle view"}]',
  4.6, 47, null, false, true, true
),
(
  'silk-turban', 'HN-SH-012', 'hijab', 4200, null,
  'Silk Turban Hijab', 'Hijab turban en soie', 'حجاب عمامة حريري',
  $$A pre-seamed silk turban hijab that creates a polished, elegant look in seconds. A signature piece for celebrations and refined everyday style.$$,
  $$Un hijab turban en soie pré-cousu qui crée un look soigné et élégant en quelques secondes. Une pièce signature pour les célébrations et un style raffiné au quotidien.$$,
  $$حجاب عمامة حريري مخيط مسبقًا يمنحك إطلالة أنيقة في ثوانٍ. قطعة مميزة للمناسبات وأسلوب يومي راقٍ.$$,
  '["Pre-seamed for easy styling","Polished, modern look","Luxurious silk sheen"]',
  '["Pré-cousu, facile à porter","Look soigné et moderne","Éclat soyeux luxueux"]',
  '["مخيط مسبقًا لسهولة التنسيق","إطلالة أنيقة وعصرية","لمعة حريرية فاخرة"]',
  '100% Mulberry Silk', '100 % soie de mûrier', '100% حرير التوت',
  '["Hand wash cold or dry clean","Steam to refresh"]',
  '["Lavage main à froid ou à sec","Rafraîchir à la vapeur"]',
  '["غسل يدوي بماء بارد أو تنظيف جاف","تجددي بالبخار"]',
  '["Gold","Bronze","Espresso"]',
  '["One Size"]', '["Silk"]', '["Eid","Work"]',
'images/silk-hijab.jpg',
  '[{"src":"images/silk-hijab.jpg","label":"Main view"},{"src":"images/hero.jpg","label":"Detail view"}]',
   4.8, 25, null, true, false, true
) on conflict (slug) do nothing;