const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { PGlite } = require('@electric-sql/pglite');
const { randomUUID } = require('node:crypto');

test('migration réelle : stock, paiements, retours, accès et recherche', async () => {
  const db = new PGlite();
  try {
    await db.exec("create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql as $$ select null::uuid $$;");
    const migrations = ['schema.sql', 'migration_variants_admin.sql', 'rls_accounts.sql', 'migration_promos_refunds.sql', 'migration_relance_analytics.sql', 'migration_blog_story.sql', 'migration_demo_reviews_home.sql', 'migration_order_cancel.sql', 'migration_promo_single_use.sql', 'migration_order_returns.sql', 'migration_guest_reviews.sql', 'migration_pending_order_lifecycle.sql', 'migration_barcode_scan.sql', 'migration_integrity_features.sql'];
    for (const file of migrations) {
      let sql = fs.readFileSync('supabase/' + file, 'utf8');
      sql = sql.replace(/create extension if not exists pgcrypto;/gi, '');
      await db.exec(sql);
    }
    await db.exec(fs.readFileSync('supabase/migration_integrity_features.sql', 'utf8'));
    assert.equal((await db.query('select commerce_schema_version() as version')).rows[0].version, 1);
    assert.equal((await db.query("select has_function_privilege('anon', 'commerce_schema_version()', 'execute') as allowed")).rows[0].allowed, false);
    const product = randomUUID(), variant = randomUUID(), user = randomUUID();
    await db.query("insert into auth.users(id) values ($1)", [user]);
    await db.query("insert into products(id,slug,sku,name_en,name_fr,name_ar,description_en,description_fr,description_ar,price_cents,category,image) values($1,'veste-test','TEST','Jacket','Veste','سترة','Long sleeves','Manches longues','أكمام طويلة',1000,'jacket','images/hero.jpg')", [product]);
    await db.query("insert into product_variants(id,product_id,color,size,stock) values($1,$2,'Beige','M',10)", [variant, product]);
    async function draft(qty, email = 'a_b@example.com') {
      const id = randomUUID(), item = randomUUID();
      await db.query("insert into orders(id,order_number,email,customer_name,address1,city,state,postal_code,country,shipping_method,total_cents,currency,user_id) values($1,$2,$3,'Test','Test','Paris','','75000','FR','standard',1000,'eur',$4)", [id, 'HN-' + id, email, user]);
      await db.query("insert into order_items(id,order_id,product_id,product_slug,product_name,image,quantity,unit_price_cents,variant_id) values($1,$2,$3,'veste-test','Veste','images/hero.jpg',$4,1000,$5)", [item, id, product, qty, variant]);
      return { id, item };
    }
    const stock = async () => (await db.query('select stock from product_variants where id=$1', [variant])).rows[0].stock;
    const first = await draft(6), second = await draft(6);
    assert.equal((await db.query('select reserve_order($1) as ok', [first.id])).rows[0].ok, true);
    assert.equal((await db.query('select reserve_order($1) as ok', [second.id])).rows[0].ok, false);
    assert.equal(await stock(), 4);
    assert.equal((await db.query('select reserve_order($1) as ok', [first.id])).rows[0].ok, true);
    assert.equal(await stock(), 4);
    await assert.rejects(db.query("select finalize_order_payment($1,'cs_test_1',999,'eur','pi_1')", [first.id]));
    await db.query("select finalize_order_payment($1,'cs_test_1',1000,'eur','pi_1')", [first.id]);
    await db.query("select finalize_order_payment($1,'cs_test_1',1000,'eur','pi_1')", [first.id]);
    await db.query("select release_order($1,'abandoned')", [first.id]);
    assert.equal(await stock(), 4);
    await db.query("update orders set shipping_status='delivered',delivered_at=now() where id=$1", [first.id]);
    const request = (await db.query("select request_return($1,$2,$3,2,'Taille inadaptée',30) as id", [user, first.id, first.item])).rows[0].id;
    assert.equal(await stock(), 4);
    await db.query("update return_requests set status='approved' where id=$1", [request]);
    await db.query('select receive_return_request($1)', [request]);
    await db.query('select receive_return_request($1)', [request]);
    assert.equal(await stock(), 6);
    await assert.rejects(db.query("select record_order_return($1,$2,5,'too-many','Test')", [first.id, first.item]));
    await db.query("select record_order_return($1,$2,4,'remaining','Test')", [first.id, first.item]);
    assert.equal(await stock(), 10);
    await db.query("update orders set status='refunded' where id=$1", [first.id]);
    await db.query('select restock_order($1)', [first.id]);
    await db.query('select restock_order($1)', [first.id]);
    assert.equal(await stock(), 10);
    await db.query("select finalize_order_payment($1,'cs_test_1',1000,'eur','pi_1')", [first.id]);
    assert.equal(await stock(), 10);
    const results = await db.query("select slug from search_products('veste', '{}', '{}', '{}', null, null)");
    assert(results.rows.some(row => row.slug === 'veste-test'));
    assert.equal((await db.query("select has_function_privilege('anon', 'reserve_order(uuid)', 'execute') as allowed")).rows[0].allowed, false);
    assert.equal((await db.query("select has_function_privilege('authenticated', 'decrement_stock(uuid,integer)', 'execute') as allowed")).rows[0].allowed, false);
    assert.equal((await db.query("select count(*)::integer as n from pg_policies where policyname='public_insert_reviews'")).rows[0].n, 0);
    const key = 'a'.repeat(64);
    assert.equal((await db.query('select consume_rate_limit($1,1,60) as ok', [key])).rows[0].ok, true);
    assert.equal((await db.query('select consume_rate_limit($1,1,60) as ok', [key])).rows[0].ok, false);
    await assert.rejects(db.query("select finalize_order_payment($1,'cs_test_1',null,'eur','pi_1')", [first.id]));
    const third = await draft(3);
    await db.query("insert into promo_codes(code,percent_off,single_use) values('ONCE',15,true)");
    await db.query("update orders set promo_code='ONCE' where id=$1", [third.id]);
    assert.equal((await db.query('select reserve_order($1) as ok', [third.id])).rows[0].ok, true);
    assert.equal(await stock(), 7);
    await db.query("select release_order($1,'abandoned')", [third.id]);
    await db.query("select release_order($1,'abandoned')", [third.id]);
    assert.equal(await stock(), 10);
    assert.equal((await db.query("select used_count from promo_codes where code='ONCE'")).rows[0].used_count, 0);
    const emptyVariant = randomUUID(), fourth = await draft(2);
    await db.query("insert into product_variants(id,product_id,color,size,stock) values($1,$2,'Black','M',0)", [emptyVariant, product]);
    await db.query("insert into order_items(id,order_id,product_slug,product_name,image,quantity,unit_price_cents,variant_id) values($1,$2,'veste-test','Veste','images/hero.jpg',1,1000,$3)", [randomUUID(), fourth.id, emptyVariant]);
    assert.equal((await db.query('select reserve_order($1) as ok', [fourth.id])).rows[0].ok, false);
    assert.equal(await stock(), 10);
    await db.query('select save_product_variants($1,$2)', [product, JSON.stringify([{ color: 'Beige', size: 'M', stock: 10, expected_stock: 10, active: true, barcode: 'HN0000001' }])]);
    assert.equal((await db.query("select id from product_variants where product_id=$1 and color='Beige'", [product])).rows[0].id, variant);
    await assert.rejects(db.query('select save_product_variants($1,$2)', [product, JSON.stringify([{ color: 'Beige', size: 'M', stock: 100, expected_stock: 9, active: true }])]));
    assert.equal(await stock(), 10);
    await db.query('update products set sizes=$2 where id=$1', [product, JSON.stringify(['XXL'])]);
    assert((await db.query('select catalog_facets() as facets')).rows[0].facets.sizes.includes('XXL'));
    const fifth = await draft(1, 'a_b@example.com'), sixth = await draft(1, 'axb@example.com');
    await db.query('update orders set user_id=null where id=any($1::uuid[])', [[fifth.id, sixth.id]]);
    await db.query("insert into order_claims(user_id,email,code_hash,expires_at) values($1,'a_b@example.com','correct',now()+interval '10 minutes')", [user]);
    assert.equal((await db.query("select claim_guest_orders($1,'wrong') as ok", [user])).rows[0].ok, false);
    assert.equal((await db.query("select claim_guest_orders($1,'correct') as ok", [user])).rows[0].ok, true);
    assert.equal((await db.query('select user_id from orders where id=$1', [fifth.id])).rows[0].user_id, user);
    assert.equal((await db.query('select user_id from orders where id=$1', [sixth.id])).rows[0].user_id, null);
    assert.equal((await db.query("select claim_guest_orders($1,'correct') as ok", [user])).rows[0].ok, false);
    const earlyRefund = await draft(2);
    await db.query('select reserve_order($1)', [earlyRefund.id]);
    assert.equal(await stock(), 8);
    await db.query("select reconcile_order_refund($1,'pi_early',1000,'eur',1000)", [earlyRefund.id]);
    await db.query("select reconcile_order_refund($1,'pi_early',1000,'eur',1000)", [earlyRefund.id]);
    await db.query("select finalize_order_payment($1,'cs_early',1000,'eur','pi_early')", [earlyRefund.id]);
    assert.equal(await stock(), 10);
    assert.equal((await db.query('select status from orders where id=$1', [earlyRefund.id])).rows[0].status, 'refunded');
    const defective = await draft(2);
    await db.query('select reserve_order($1)', [defective.id]);
    await db.query("select finalize_order_payment($1,'cs_defective',1000,'eur','pi_defective')", [defective.id]);
    await db.query('update orders set refund_restock=false where id=$1', [defective.id]);
    await db.query("select reconcile_order_refund($1,'pi_defective',1000,'eur',1000)", [defective.id]);
    assert.equal(await stock(), 8);
    await db.query("select reconcile_order_refund($1,'pi_defective',1000,'eur',100)", [defective.id]);
    assert.equal((await db.query('select refunded_cents from orders where id=$1', [defective.id])).rows[0].refunded_cents, 1000);
    assert.equal((await db.query("select start_admin_reset('otp-hash') as ok")).rows[0].ok, true);
    assert.equal((await db.query("select start_admin_reset('different') as ok")).rows[0].ok, false);
    assert.equal((await db.query("select apply_admin_reset('wrong','new-hash') as ok")).rows[0].ok, false);
    assert.equal((await db.query("select apply_admin_reset('otp-hash','new-hash') as ok")).rows[0].ok, true);
    assert.equal((await db.query("select apply_admin_reset('otp-hash','other-hash') as ok")).rows[0].ok, false);
    assert.equal((await db.query("select (value->>'token_version')::integer as version from settings where key='admin_auth'")).rows[0].version, 1);
    assert.deepEqual((await db.query("select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and not c.relrowsecurity")).rows, []);
    await db.query("insert into settings(key,value) values($1,$2)", ['tiktok:' + product, JSON.stringify({ manufacturer_ids: 'private-test', rp_ids: 'private-test' })]);
    await db.query("insert into settings(key,value) values('product-color:gris atelier',$1)", [JSON.stringify({ name: 'gris atelier', hex: '#BCC4CC' })]);
    await db.exec('grant select, insert, update on public.settings to anon, authenticated');
    for (const role of ['anon', 'authenticated']) {
      await db.exec('set role ' + role);
      try {
        assert.equal((await db.query("select value from settings where key=$1", ['tiktok:' + product])).rows.length, 0);
        assert.equal((await db.query("select value from settings where key='product-color:gris atelier'")).rows.length, 0);
        await assert.rejects(db.query("insert into settings(key,value) values('product-color:unauthorized','{}')"));
        assert.equal((await db.query("update settings set value='{}' where key='product-color:gris atelier' returning key")).rows.length, 0);
        await assert.rejects(db.query("insert into settings(key,value) values('tiktok:unauthorized','{}')"));
        assert.equal((await db.query("update settings set value='{}' where key=$1 returning key", ['tiktok:' + product])).rows.length, 0);
      } finally { await db.exec('reset role'); }
    }
    const rounding = await draft(3);
    await db.query("update orders set status='paid' where id=$1", [rounding.id]);
    await db.query('update order_items set net_total_cents=203 where id=$1', [rounding.item]);
    for (let i = 0; i < 3; i++) await db.query("select record_order_return($1,$2,1,$3,'Test')", [rounding.id, rounding.item, 'rounding-' + i]);
    assert.equal((await db.query('select sum(total_refund_cents)::integer as cents from order_returns where order_id=$1', [rounding.id])).rows[0].cents, 203);
  } finally { await db.close(); }
});
